FROM ubuntu:trusty
MAINTAINER Jim Rybarski <jim@rybarski.com>

RUN \
  apt-get update && \
  apt-get install -y nginx && \
  rm -rf /var/lib/apt/lists/* && \
  chown -R www-data:www-data /var/lib/nginx

RUN mkdir -p /srv/www/
COPY ./frontend /srv/www/
RUN mv /srv/www/config/temperature.controller.conf /etc/nginx/conf.d/temperature.controller.conf
RUN mv /srv/www/config/nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx

CMD ["nginx"]