# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kp', models.FloatField(default=0.0)),
                ('ki', models.FloatField(default=0.0)),
                ('kd', models.FloatField(default=0.0)),
                ('max_accumulated_error', models.FloatField(default=10.0)),
                ('min_accumulated_error', models.FloatField(default=-10.0)),
                ('max_power', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('steps', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpidapi.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='scientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpidapi.Scientist'),
        ),
    ]
